services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2023-11-01T01-57-10Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    networks:
      - siesta-net
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - siesta-net

  kafka:
    container_name: siesta-kafka
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9093,OUTSIDE://siesta-kafka:9092
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    #    volumes:
    #      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - siesta-net

  init-kafka:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:9093 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9093 --create --if-not-exists --topic test --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9093 --list
      "
    networks:
      - siesta-net
  postgres:
    container_name: siesta-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: metrics
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - siesta-net

  createbuckets: #automatically creates the required bucket
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/siesta;
      /usr/bin/mc policy download myminio/siesta;
      exit 0;
      "
    networks:
      - siesta-net

  scylla:
    image: scylladb/scylla:5.2
    container_name: scylla
    command: --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    ports:
      - "9042:9042"   # CQL native transport
      - "9180:9180"   # REST API (optional)

#  cassandra:
#    container_name: cassandra
#    image: cassandra:4.1
#    ports:
#      - "9042:9042"
#    environment:
#      - CASSANDRA_CLUSTER_NAME=SiestaCluster
#      - CASSANDRA_DC=datacenter1
#      - CASSANDRA_RACK=rack1
#      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
#      - CASSANDRA_NUM_TOKENS=128
#    volumes:
#      - cassandra_data:/var/lib/cassandra
#    networks:
#      - siesta-net
#    healthcheck:
#      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
#      interval: 30s
#      timeout: 10s
#      retries: 5


  # preprocess:
  #   build:
  #     context: .
  #     dockerfile: dockerbase/REST.Dockerfile
  #   ports:
  #     - "8000:8000"
  #     - "4040:4040"
  #   networks:
  #     - siesta-net
  #   volumes:
  #     - preprocesses:/app/pythonAPI/dbSQL
  #     - ./experiments/input:/app/pythonAPI/uploadedfiles
  #   environment:
  #     s3accessKeyAws: minioadmin
  #     s3ConnectionTimeout: 600000
  #     s3endPointLoc: http://minio:9000
  #     s3secretKeyAws: minioadmin


  preprocess:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: preprocess
    environment:
      - s3accessKeyAws=minioadmin
      - s3ConnectionTimeout=60
      - s3endPointLoc=http://minio:9000
      - s3secretKeyAws=minioadmin
      - CASSANDRA_HOST=http://cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - JAVA_TOOL_OPTIONS=-XX:-UseContainerSupport --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/sun.nio.cs=ALL-UNNAMED --add-opens=java.base/sun.security.action=ALL-UNNAMED --add-opens=java.base/sun.util.calendar=ALL-UNNAMED --add-opens=java.security.jgss/sun.security.krb5=ALL-UNNAMED --add-opens=java.base/java.lang.ref=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED --add-opens=java.base/java.time.zone=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED
    volumes:
      - ./experiments/input:/app/input
      - ./experiments/output:/app/output
    entrypoint:
      - /opt/spark/bin/spark-submit
      - --master
      - local[2]
      - --driver-memory
      - 4g
      - --executor-memory
      - 2g
      - --conf
      - spark.sql.adaptive.enabled=true
      - --conf
      - spark.sql.adaptive.coalescePartitions.enabled=true
      - --conf
      - spark.eventLog.enabled=true
      - --conf
      - spark.eventLog.dir=/tmp/spark-events
      - preprocess.jar
    command: ["--logname", "bpic2017", "--file", "/app/input/bpic2017.xes"]
    networks:
      - siesta-net

x-disabled:
  send_events: #send example events in form .withTimestamp
    build:
      context: .
      dockerfile: send_events.Dockerfile
    networks:
      - siesta-net


networks:
  siesta-net:
    name: siesta-net
    # external: true

volumes:
  minio_storage: {}
  preprocesses: {}
  postgres-data: {}
  cassandra_data: {}
