# Suppress INFO logs, show only WARN and ERROR
status = error
name = SparkLogConfig

filters = threshold
filter.threshold.type = ThresholdFilter
filter.threshold.level = WARN

appenders = console
appender.console.type = Console
appender.console.name = STDOUT
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n

rootLogger.level = WARN
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = STDOUT

logger.hadoop.name = org.apache.hadoop.metrics2
logger.hadoop.level = ERROR
